@echo off

echo  ______   ______   ______   ___   ___   ______   __       __           
echo /_____/\ /_____/\ /_____/\ /__/\ /__/\ /_____/\ /_/\     /_/\          
echo \:::__\/ \:::_ \ \\::::_\/_\::\ \\  \ \\::::_\/_\:\ \    \:\ \         
echo  \:\ \  __\:(_) \ \\:\/___/\\::\/_\ .\ \\:\/___/\\:\ \    \:\ \        
echo   \:\ \/_/\\: ___\/ \_::._\:\\:: ___::\ \\::___\/_\:\ \____\:\ \____   
echo    \:\_\ \ \\ \ \     /____\:\\: \ \\::\ \\:\____/\\:\/___/\\:\/___/\  
echo     \_____\/ \_\/     \_____\/ \__\/ \::\/ \_____\/ \_____\/ \_____\/  

echo CPshell v1.2
echo Created by: Disasterocks + Watrmeln
echo UI and stuff by: Watrmeln
echo ASCII Art generated by http://patorjk.com/software/taag/ by Patrick Gillespie

echo https://repository13.github.io/CPShell/
echo Thank you for using CPshell!